<a href="https://colab.research.google.com/github/nur545315-oss/PM_TuRi2_Preprocessing_Nurkhotimah/blob/main/PM_P4_Nurkhotimah.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Langkah 1 - Menangani nilai hilang (imputasi median/modus)

In [17]:
import pandas as pd
import numpy as np

data = {
    'usia': [25, 30, np.nan, 35, 28, 40, np.nan, 32, 45, 27],
    'pendapatan': [3000000, 4500000, 5000000, np.nan, 3500000, 7000000, 6000000, np.nan, 8500000, 4000000],
    'pendidikan': ['SMA', 'S1', 'S1', 'S2', 'SMA', 'S2', 'S1', 'S1', 'S2', 'SMA'],
    'kota': ['Kuningan', 'Cirebon', 'Majalengka', 'Kuningan', 'Cirebon', 'Majalengka', 'Kuningan', 'Cirebon', 'Majalengka', 'Kuningan'],
    'membeli': ['Tidak', 'Ya', 'Ya', 'Ya', 'Tidak', 'Ya', 'Ya', 'Tidak', 'Ya', 'Tidak']
}

df = pd.DataFrame(data)

df
df['usia'] = df['usia'].fillna(df['usia'].median())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].median())

# Langkah 2 - Memisahkan fitur (X) dan label (Y)

In [18]:
x = df.drop(columns=['membeli'])
y = df['membeli']

# Langkah 3 - Encoding kategorikal (ordinal & one-hot)

In [19]:
x['pendidikan'] = x['pendidikan'].map({'SMA': 0, 'S1': 1, 'S2': 2})
x = pd.get_dummies(x, columns=['kota'], dtype=int)
y = y.map({'Tidak':0, 'Ya':1})

# Langkah 4 - Membagi dta (SEBELUM scaling)

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42)

# Langkah 5 - Pensklaan (fit pada latih, transform pada latih & uji)

In [21]:
from sklearn.preprocessing import StandardScaler
num = ['usia', 'pendapatan', 'pendidikan']
sc = StandardScaler()
x_train[num] = sc.fit_transform(x_train[num])
x_test[num] = sc.transform(x_test[num])

# Langkah 6 - Verifikasi: tidak ada nilai hilang, semua numerik, skala seragam

In [22]:
print(x.dtypes)
print(y.dtypes)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

print(x_scaled)

usia               float64
pendapatan         float64
pendidikan           int64
kota_Cirebon         int64
kota_Kuningan        int64
kota_Majalengka      int64
dtype: object
int64
[[-1.27586207 -1.33417397 -1.29099445 -0.65465367  1.22474487 -0.65465367]
 [-0.4137931  -0.38119256  0.          1.52752523 -0.81649658 -0.65465367]
 [-0.24137931 -0.06353209  0.         -0.65465367 -0.81649658  1.52752523]
 [ 0.44827586 -0.22236233  1.29099445 -0.65465367  1.22474487 -0.65465367]
 [-0.75862069 -1.0165135  -1.29099445  1.52752523 -0.81649658 -0.65465367]
 [ 1.31034483  1.20710978  1.29099445 -0.65465367 -0.81649658  1.52752523]
 [-0.24137931  0.57178884  0.         -0.65465367  1.22474487 -0.65465367]
 [-0.06896552 -0.22236233  0.          1.52752523 -0.81649658 -0.65465367]
 [ 2.17241379  2.16009119  1.29099445 -0.65465367 -0.81649658  1.52752523]
 [-0.93103448 -0.69885303 -1.29099445 -0.65465367  1.22474487 -0.65465367]]


**Latihan Mandiri**

# 1. Ganti imputasi usia menjadi mean; bandingkan hasilnya

In [23]:
df_mean = df.copy()

df_mean['usia'] = df_mean['usia'].fillna(df_mean['usia'].mean())

print("Hasil imputasi dengan mean:")
print(df_mean['usia'])

print("Mean usia:", df['usia'].mean())
print("Median usia:", df['usia'].median())

Hasil imputasi dengan mean:
0    25.0
1    30.0
2    31.0
3    35.0
4    28.0
5    40.0
6    31.0
7    32.0
8    45.0
9    27.0
Name: usia, dtype: float64
Mean usia: 32.4
Median usia: 31.0


# 2. Gunakan MinMaxScaler(0-1) sebagai ganti StandarScaler; tampilkan describe()

In [24]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

x_minmax = scaler.fit_transform(x)
x_minmax = pd.DataFrame(x_minmax, columns=x.columns)
x_minmax.describe()

,usia,pendapatan,pendidikan,kota_Cirebon,kota_Kuningan,kota_Majalengka
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.370000,0.381818,0.500000,0.300000,0.400000,0.300000
std,0.305687,0.301664,0.408248,0.483046,0.516398,0.483046
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.175000,0.204545,0.125000,0.000000,0.000000,0.000000
50%,0.300000,0.318182,0.500000,0.000000,0.000000,0.000000
75%,0.462500,0.500000,0.875000,0.750000,1.000000,0.750000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000


# 3. Tambahkan kolom kategorikal baru dan terapkan one-hot encoding

# 4. Jelaskan mengapa fit_transform pada latih tetapi hanya transform pada uji

Karena fit_transform digunakan untuk mempelajari parameter preprocessing dari data latih sekaligus mengubah datanya, sedangkan data uji hanya menggunakan transform agar tidak terjadi data leakage.

**REFLEKSI**

# 1. Mengapa urutan 'split dulu, baru scaling' penting?

Agar informasi dari data uji tidak ikut digunakan saat proses scaling pada data latih, sehingga dapat mencegah data leakage dan menghasilkan evaluasi model yang lebih valid.

# 2. Kapan label encoding dan kapan one-hot encoding?

Label encoding digunakan untuk kategori yang memiliki urutan, sedangkan one-hot encoding digunakan untuk kategori yang tidak memiliki urutan.

# 3. Apa perbedaan normalisasi dan standardisasi?

Normalisasi mengubah nilai data ke rentang tertentu, biasanya 0–1. Sedangkan standardisasi mengubah data berdasarkan mean dan standar deviasi, sehingga data memiliki rata-rata sekitar 0 dan standar deviasi sekitar 1.